dubbo:
  application:
    name: dubbo-application-provider
  registry:
    address: 121.36.168.192:2181,121.36.168.192:2182,121.36.168.192:2183
    protocol: zookeeper
  scan:
    base-packages: com.example.dubboprovider.service.impl
  protocol:
    name: rest
    port: 8083
#  protocols:
#    key1:
#      id: dubbo1
#      name: dubbo
#      port: 20881

